import { useEffect, useState } from 'react';
import { ArrowUpRight, Search, Radio } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import './index-preview.css';
type Source={id:string;name:string;url:string;towns:string[];kind:string;status:string;checkedAt:string|null;enabled:boolean;collecting:boolean;itemCount:number};
type Item={id:string;title:string;url:string;source:string;towns:string[];date:string|null;destination:string;aiEvidence:string;localEvidence:string;status:string;kind:string|null};
type Data={fetchedAt:string;sources:Source[];items:Item[];observations:number;classified:number;classificationPending:number};
const dateLabel=(v:string|null)=>v?new Date(v).toLocaleDateString('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',year:'numeric'}):'Date unknown';
export default function IndexPreview(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState('');
 const [query,setQuery]=useState(''),[town,setTown]=useState('All island');
 useEffect(()=>{const controller=new AbortController();let stopped=false;
 async function refresh(){try{const r=await fetch('/api/aqai/preview',{signal:controller.signal});if(!r.ok)throw Error();const next=await r.json();if(!stopped){setData(next);setError('');}}catch{if(!stopped)setError('Database refresh failed. Displayed data, if any, is from the last successful refresh.');}}
 refresh();const timer=setInterval(refresh,60000);return()=>{stopped=true;controller.abort();clearInterval(timer);};},[]);
 const matches=(towns:string[],text:string)=>(town==='All island'||towns.includes(town))&&text.toLowerCase().includes(query.toLowerCase());
 const sources=(data?.sources??[]).filter(s=>matches(s.towns,`${s.name} ${s.kind}`));
 const items=(data?.items??[]).filter(i=>matches(i.towns,`${i.title} ${i.source} ${i.aiEvidence}`));
 return <div className="aq-index"><header className="aq-header"><a href="/index-preview" className="aq-brand">Aquidneck<span>AI</span><small>THE LOCAL AI INDEX</small></a><a href="#coverage">Source coverage <ArrowUpRight size={16}/></a></header><main>
 <div className="aq-kicker"><Radio size={15}/> NEWPORT · MIDDLETOWN · PORTSMOUTH</div>
 <section className="aq-intro"><div><h1>AI is happening here.<br/><em>Find your connection.</em></h1><p>Local programs, news, research, and opportunities connecting Aquidneck Island and AI.</p></div><aside><span>LIVE DATABASE · STAGING</span><strong>Evidence comes first.</strong><p>Published events pass source, place, AI evidence, and date checks. Archive resources remain review material.</p></aside></section>
 {error&&<p role="alert">{error}</p>}{!data&&!error&&<p role="status">Loading the live index…</p>}
 {data&&<p className="aq-caption">{data.observations} collected items · {data.classified} assessed · {data.classificationPending} pending · Refreshed {new Date(data.fetchedAt).toLocaleTimeString()} · Refreshes every minute</p>}
 <section className="aq-search" aria-label="Search the index"><label htmlFor="aq-search"><Search size={20}/><Input id="aq-search" type="search" placeholder="Search organizations or AI topics" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="aq-towns">{['All island','Newport','Middletown','Portsmouth'].map(name=><Button key={name} variant="ghost" aria-pressed={town===name} onClick={()=>setTown(name)}>{name}</Button>)}</div></section>
 <div className="aq-columns"><section aria-label="Index candidates">{[{label:'Current local AI',key:'current_review'},{label:'Archive resources',key:'archive_review'},{label:'Date needs checking',key:'date_review'}].map(section=>{const list=items.filter(i=>i.destination===section.key);return <section key={section.key}><div className="aq-section-heading"><h2>{section.label}</h2><span>{list.length}</span></div>{list.map(i=><article key={i.id} className="aq-item"><div className="aq-item-top"><span>{dateLabel(i.date)}</span><span>{i.status==='published'?'Published · Source verified':'Unpublished · Needs verification'}</span></div><h3><a href={i.url} target="_blank" rel="noreferrer">{i.title}<ArrowUpRight size={22}/></a></h3><p>{i.source}</p>{i.aiEvidence&&<p><strong>AI evidence:</strong> “{i.aiEvidence}”</p>}<p><strong>Local connection:</strong> {i.localEvidence} {i.status!=='published'&&<small>(source context; awaiting verification)</small>}</p><footer><span>{i.towns.join(' · ')}</span><a href={i.url} target="_blank" rel="noreferrer">Original source ↗</a></footer></article>)}{data&&!list.length&&<p className="aq-caption">No matching {section.label.toLowerCase()} in this limited collection.</p>}</section>;})}<div className="aq-note"><strong>Built on original sources.</strong><p>Collection, AI assessment, and publication are separate. Empty results do not mean there is no local AI activity.</p></div></section>
 <section id="coverage" aria-labelledby="aq-coverage"><div className="aq-section-heading"><h2 id="aq-coverage">Coverage notebook</h2><span>{sources.length} endpoints</span></div><p className="aq-caption">{data?.sources.filter(s=>s.checkedAt).length??0} checked · {data?.sources.filter(s=>s.collecting).length??0} collecting automatically · {data?.sources.filter(s=>s.enabled&&!s.collecting).length??0} awaiting setup</p><div className="aq-source-list">{sources.map(s=><article key={s.id}><div><a href={s.url} target="_blank" rel="noreferrer">{s.name} <ArrowUpRight size={14}/></a><small>{s.towns.join(' · ')} · {s.kind}</small></div><p>{s.status==='parsed'?'Feed parsed':s.status==='failed'?'Last check failed':'Not yet checked'} · {s.collecting?'Collecting automatically':s.enabled?'Requested · Awaiting setup':'Recurring off'}</p><small>{s.checkedAt?`${s.itemCount} items · Checked ${dateLabel(s.checkedAt)}`:'Listed; collection not yet verified'}</small></article>)}</div></section></div>
 <footer className="aq-footer"><span>AquidneckAI · A local information project</span><span>Supabase-backed staging · Strict event publication rules active</span></footer></main></div>;
}
